import { mkdirSync, writeFileSync, chmodSync, existsSync, readFileSync, rmSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const CONFIG_DIR = join(homedir(), ".citizen");
const CONFIG_PATH = join(CONFIG_DIR, "config.json");

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DEFAULT_CONFIG = {
  tools: {
    "claude-code": {
      command: "claude",
      args: ["{prompt}"],
      label: "Claude Code",
    },
    cursor: {
      deepLink: "cursor://anysphere.cursor-deeplink/prompt?text={prompt}",
      label: "Cursor",
    },
    opencode: {
      command: "opencode",
      args: ["-p", "{prompt}"],
      label: "OpenCode",
    },
    aider: {
      command: "aider",
      args: ["--message", "{prompt}"],
      label: "Aider",
    },
    codex: {
      command: "codex",
      args: ["{prompt}"],
      label: "Codex CLI",
    },
    vscode: {
      deepLink: "vscode://vscode.git/clone?url={repoUrl}",
      label: "VS Code",
    },
  },
  defaultTool: "claude-code",
};

function ensureDir(dir: string) {
  mkdirSync(dir, { recursive: true });
}

function getHandlerSourcePath(): string {
  return join(__dirname, "handler.js");
}

function getHandlerPath(): string {
  return join(CONFIG_DIR, "handler.js");
}

function getNodePath(): string {
  return process.execPath;
}

function setupMacOS() {
  const appDir = join(CONFIG_DIR, "Citizen.app");
  const handlerPath = getHandlerPath();
  const nodePath = getNodePath();

  // Remove old .app if it exists so osacompile can write cleanly
  if (existsSync(appDir)) {
    rmSync(appDir, { recursive: true });
  }

  // Build an AppleScript app that receives the URL via the "open location"
  // Apple Event (macOS sends URLs as events, not CLI args).
  const appleScript = `on open location theURL
  do shell script quoted form of "${nodePath}" & " " & quoted form of "${handlerPath}" & " " & quoted form of theURL & " &> /tmp/citizen-handler.log &"
end open location`;

  const scriptPath = join(CONFIG_DIR, "citizen-handler.applescript");
  writeFileSync(scriptPath, appleScript);

  try {
    execSync(`osacompile -o "${appDir}" "${scriptPath}"`);
  } catch (err) {
    console.error("Failed to compile AppleScript app:", err);
    process.exit(1);
  }

  // Patch the Info.plist generated by osacompile to add the citizen:// URL scheme
  const plistPath = join(appDir, "Contents", "Info.plist");
  const plistContent = readFileSync(plistPath, "utf-8");

  const urlSchemeBlock = `\t<key>CFBundleIdentifier</key>
\t<string>dev.citizen.cli</string>
\t<key>CFBundleURLTypes</key>
\t<array>
\t\t<dict>
\t\t\t<key>CFBundleURLName</key>
\t\t\t<string>Citizen Protocol</string>
\t\t\t<key>CFBundleURLSchemes</key>
\t\t\t<array>
\t\t\t\t<string>citizen</string>
\t\t\t</array>
\t\t</dict>
\t</array>
`;

  // Insert before the final </dict></plist>, not the first nested </dict>
  const patched = plistContent.replace(
    /(<\/dict>\s*<\/plist>\s*)$/,
    `${urlSchemeBlock}</dict>\n</plist>\n`,
  );
  writeFileSync(plistPath, patched);

  // Register with Launch Services
  try {
    execSync(
      `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -R "${appDir}"`
    );
  } catch {
    console.warn("Warning: Could not register with Launch Services. The app may still work.");
  }

  // Clean up temp script
  try { rmSync(scriptPath); } catch { /* ignore */ }

  console.log(`  Created ${appDir}`);
  console.log("  Registered citizen:// protocol handler with macOS");
}

function setupLinux() {
  const appsDir = join(homedir(), ".local", "share", "applications");
  ensureDir(appsDir);

  const handlerPath = getHandlerPath();
  const nodePath = getNodePath();

  const desktopEntry = `[Desktop Entry]
Name=Citizen
Comment=Citizen protocol handler
Exec=${nodePath} ${handlerPath} %u
Type=Application
NoDisplay=true
MimeType=x-scheme-handler/citizen;
`;

  const desktopPath = join(appsDir, "citizen.desktop");
  writeFileSync(desktopPath, desktopEntry);

  try {
    execSync(`xdg-mime default citizen.desktop x-scheme-handler/citizen`);
  } catch {
    console.warn("Warning: Could not set default handler. Try running 'xdg-mime default citizen.desktop x-scheme-handler/citizen' manually.");
  }

  console.log(`  Created ${desktopPath}`);
  console.log("  Registered citizen:// protocol handler with XDG");
}

async function registerWithServer(apiKey: string, serverUrl: string) {
  try {
    const res = await fetch(`${serverUrl}/api/cli/register`, {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (!res.ok) {
      const body = await res.json().catch(() => ({}));
      console.warn(`  Warning: Server registration failed: ${(body as { error?: string }).error ?? res.statusText}`);
      return;
    }
    const data = await res.json() as { username?: string };
    console.log(`  Registered CLI installation for @${data.username}`);
  } catch {
    console.warn("  Warning: Could not reach server. CLI works locally, but one-click launch from the web won't be enabled until you register.");
  }
}

export async function setup(apiKey?: string, serverUrl = "https://citizen.dev") {
  console.log("\nSetting up Citizen CLI...\n");

  // 1. Create config directory and copy handler
  ensureDir(CONFIG_DIR);
  copyFileSync(getHandlerSourcePath(), getHandlerPath());
  writeFileSync(join(CONFIG_DIR, "package.json"), '{"type":"module"}\n');
  console.log(`  Installed handler at ${getHandlerPath()}`);

  // 2. Write default config (preserve existing)
  if (existsSync(CONFIG_PATH)) {
    console.log(`  Config already exists at ${CONFIG_PATH}`);
    // Merge new tools into existing config
    const existing = JSON.parse(readFileSync(CONFIG_PATH, "utf-8"));
    for (const [key, value] of Object.entries(DEFAULT_CONFIG.tools)) {
      if (!existing.tools[key]) {
        existing.tools[key] = value;
      }
    }
    writeFileSync(CONFIG_PATH, JSON.stringify(existing, null, 2));
    console.log("  Merged any new default tools into existing config");
  } else {
    writeFileSync(CONFIG_PATH, JSON.stringify(DEFAULT_CONFIG, null, 2));
    console.log(`  Created config at ${CONFIG_PATH}`);
  }

  // 3. Register protocol handler (OS-specific)
  if (process.platform === "darwin") {
    setupMacOS();
  } else if (process.platform === "linux") {
    setupLinux();
  } else if (process.platform === "win32") {
    console.log("  Windows support coming soon. For now, use the clipboard fallback.");
  } else {
    console.log(`  Unsupported platform: ${process.platform}`);
  }

  // 4. Register with server (enables one-click launch from web)
  if (apiKey) {
    await registerWithServer(apiKey, serverUrl);
  } else {
    console.log("\n  Tip: To enable one-click launch from the web, re-run with your API key:");
    console.log("    citizen setup --key <your-api-key>");
  }

  console.log("\nDone! Click any 'Code Agent' button on Citizen to launch your tool.\n");
  console.log(`  Config: ${CONFIG_PATH}`);
  console.log("  Add custom tools by editing the config file.\n");
}

export function uninstall() {
  console.log("\nRemoving Citizen CLI...\n");

  if (process.platform === "darwin") {
    const appDir = join(CONFIG_DIR, "Citizen.app");
    if (existsSync(appDir)) {
      execSync(`rm -rf "${appDir}"`);
      console.log(`  Removed ${appDir}`);
      try {
        execSync(
          `/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -u "${appDir}"`
        );
      } catch {
        // May already be unregistered
      }
    }
  } else if (process.platform === "linux") {
    const desktopPath = join(homedir(), ".local", "share", "applications", "citizen.desktop");
    if (existsSync(desktopPath)) {
      execSync(`rm "${desktopPath}"`);
      console.log(`  Removed ${desktopPath}`);
    }
  }

  console.log("  Protocol handler removed.");
  console.log(`  Config preserved at ${CONFIG_PATH} (delete manually if needed).\n`);
}

export function listTools() {
  if (!existsSync(CONFIG_PATH)) {
    console.log("No config found. Run 'citizen setup' first.");
    return;
  }

  const config = JSON.parse(readFileSync(CONFIG_PATH, "utf-8"));
  console.log("\nConfigured tools:\n");

  for (const [id, tool] of Object.entries(config.tools) as [string, { label: string; command?: string; deepLink?: string }][]) {
    const type = tool.deepLink ? "deep link" : "terminal";
    const defaultMark = id === config.defaultTool ? " (default)" : "";
    console.log(`  ${tool.label} [${id}] - ${type}${defaultMark}`);
  }

  console.log(`\n  Config: ${CONFIG_PATH}\n`);
}
